//create a new user

//import prisma client
import { PrismaClient } from "@prisma/client";
// this client is autogenerated from based on what our migrations look like

const prisma = new PrismaClient();

async function main() {
  // client queries here
}

//standard promise to start and end connection and log errors

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
