//create a new user

//import prisma client
import { PrismaClient } from "@prisma/client";
// this client is autogenerated from based on what our migrations look like

const prisma = new PrismaClient({
  log: ["info", "query"],
});

async function main() {
  // client queries here

  //adding data
  await prisma.user.create({
    data: {
      email: "sagnik3212@gmail.com",
      name: "sagnik2",
    },
  });
}

//standard promise to start and end connection and log errors

main()
  .then(async () => {
    console.log(`Done with the query!`);
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
