//create a new user

//import prisma client
import { PrismaClient } from "@prisma/client";
// this client is autogenerated from based on what our migrations look like

const prisma = new PrismaClient();

async function main() {
  // client queries here

  //adding data
  await prisma.post.create({
    data: {
      title: "The Lambda Papers",
      content: "asdfghjikl",
      author: {
        connect: {
          //connect with the already created User table with id 1
          id: 1,
        },
      },
    },
  });
}

//standard promise to start and end connection and log errors

main()
  .then(async () => {
    console.log(`Done with the query!`);
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
